### ISSUE TITLE
Polymer.Templatizer is not a constructor

### ISSUE THREAD

**Issue by yonathan9669** [PolymerLabs/iron-overlay#5] opened 2017-02-22 17:59 UTC
Using iron-overlay#use-2.0, an error it's been generated on the _createRenderer function that's preventing the element to be used.

> Uncaught TypeError: Polymer.Templatizer is not a constructor
at HTMLElement._createRenderer (iron-overlay.html:362)...

The error is been thrown HERE
`[Lines 361-382]: _createRenderer() {const templatizer = new Polymer.Templatizer(); ... }`

This is happening in all browsers. I already made a research about it and didn't get anything that could help me.

I'm using `polymer-cli@0.17.0` to serve the code.
This are my bower dependences:

> "dependencies": {
    "blockingElements": "PolymerLabs/blockingElements",
    "inert": "WICG/inert",
    "iron-overlay": "polymerlabs/iron-overlay#use-2.0"
  }

I already flush my bower cache; Force to download the latest versions; Use the exactly required dependences versions but nothing change I'm just getting the same error everywhere.

I did check that the Polymer.Templatizer behavior it's there.
I really don't know what else should I do.

If you need any extra information please let me know.
Cheers. 👍🏼

**Comment by valdrinkoshi** [comment] 2017-02-23 00:24
This was caused by an update on polymer#2.0-preview, I've updated the branch to use the latest and greatest `Polymer.Templatize` in this commit https://github.com/PolymerLabs/iron-overlay/pull/3/commits/733d348b6782f733f4b33b6635c8d45a860248dc
Closing, LMK if you're still facing issues and I'll reopen this issue 👌

**Closed as completed by valdrinkoshi** 2017-02-23 00:24 UTC

**Comment by yonathan9669** [comment] 2017-02-23 13:47
@valdrinkoshi awesome... 😁 It works like a charm, thanks very much.

I solve my issue using other technique, but I will probably use this element soon.
Thanks again. 👍🏼
